[tags]
    # File Uploads
    [tags.attachments]
        max_size = 20000000
        # serve_if_field_present = "message"

    # User Avatars
    [tags.avatars]
        max_size = 4000000
        restrict_content_type = "Image"
        
    # Channel / Server Icons
    [tags.icons]
        max_size = 4000000
        restrict_content_type = "Image"
        
    # Banners
    [tags.banners]
        enabled = false
        max_size = 6000000
        restrict_content_type = "Image"
